spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false

server:
  error:
    whitelabel:
      enabled: false

management:
  endpoint:
    health:
      show-details: never

sentry:
  dsn: ${APP_SENTRY_DSN}
  traces-sample-rate: 1.0

decorator:
  datasource:
    p6spy:
      enable-logging: false
