spring:
  config:
    activate:
      on-profile: prod
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false

server:
  error:
    whitelabel:
      enabled: false

decorator:
  datasource:
    p6spy:
      enable-logging: false
