spring:
  profiles:
    group:
      local: local
      prod: prod
    default: local
  mvc:
    log-resolved-exception: false
  data:
    mongodb:
      uri: ${APP_MONGO_DB_URI}
    redis:
      url: ${APP_REDIS_URL}
  security:
    user:
      name: ${APP_SECURITY_USERNAME}
      password: ${APP_SECURITY_PASSWORD}
      roles: ADMIN
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  thymeleaf:
    cache: false
  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  address: 0.0.0.0
  port: 8081
  tomcat:
    threads:
      max: 500
      min-spare: 20
    max-connections: 10000
    max-http-form-post-size: -1
    max-swallow-size: -1
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include:
          - beans
          - env
          - health
          - mappings
          - metrics
          - prometheus
  endpoint:
    health:
      show-details: always

app:
  security:
    jwt-secret: ${APP_JWT_SECRET}
    jwt-token-duration-seconds: ${APP_JWT_TOKEN_DURATION_SECONDS}
    master-api-key: ${APP_MASTER_API_KEY}
  main-api-host: ${APP_MAIN_API_HOST}
