spring:
  config:
    activate:
      on-profile: prod
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false

server:
  error:
    whitelabel:
      enabled: false

management:
  endpoint:
    health:
      show-details: never
